name = "CoreMathPure"
uuid = "e4c361a0-7b2e-4f18-b5a3-9c4a0f8e2d1b"
version = "0.1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]

[compat]
julia = "1.6"
